name: Development
run-name: Compilation & Quality Checks
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - '*'
      - '!dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install & Compile UI
        run: |
          npm install
          npm run-script build
      - name: Install & Compile Backend
        run: |
          cd backend
          npm install
          npm run-script build
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: UI ViTest
        run: |
          npm install
          npm run-script test