name: Development
run-name: Compilation & Quality Checks
on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install & Build
        run: |
          npm install
          npm run-script build
      - name: Unit Test
        run: |
          npm install
          npm run-script test