name: Development
run-name: test
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          VITE_NEWS_API_KEY: ${{ secrets.VITE_NEWS_API_KEY }}
      - name: Test
        run: |
          npm install
          npm run-script test