name: Development
run-name: Compilation & Quality Checks
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - '*'
      - '!dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install & Compile UI
        run: |
          npm install
          npm run-script build
      - name: Install & Compile Backend
        run: |
          cd backend
          npm ci
          npm run-script build
  frontend-unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: UI ViTest
        run: |
          npm ci
          npm run-script test
  backend-unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: ExpressJS Unit Tests
        run: |
          cd backend
          npm run-script test:ci