name: Deploy Nyuusu
run-name: deploy-nyuusu
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          VITE_NEWS_API_KEY: ${{ secrets.VITE_NEWS_API_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build