name: Nyuusu Pull-Request
run-name: nyuusu-pull-request
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          VITE_NEWS_API_KEY: ${{ secrets.VITE_NEWS_API_KEY }}
      - name: Test
        run: |
          npm install
          npm run-script test